# Generated by Django 4.0.4 on 2024-04-10 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
        ('vehiculo', '0001_initial'),
        ('rh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio', models.IntegerField(choices=[(0, 'Sin servicio'), (1, 'Escolta mixta'), (2, 'Escolta personal'), (3, 'Escolta vehicular'), (4, 'Monitoreo'), (5, 'Seguridad en evento'), (6, 'Traslado de valores'), (7, 'Vigilancia en bienes muebles'), (7, 'Otro')], default=1, verbose_name='Servicio')),
                ('otro_servicio', models.CharField(blank=True, max_length=100, null=True, verbose_name='Otro servicio')),
                ('detalle', models.CharField(blank=True, max_length=256, null=True, verbose_name='Detalle')),
                ('ubicacion', models.JSONField(verbose_name='Ubicación')),
                ('cobro', models.DecimalField(decimal_places=2, default=0, max_digits=11, verbose_name='Cobro')),
                ('fecha_inicial', models.DateField(verbose_name='Inicia')),
                ('fecha_termina', models.DateField(blank=True, null=True, verbose_name='Termina')),
                ('fecha_alta', models.DateField(auto_now_add=True, verbose_name='Alta')),
                ('fecha_baja', models.DateField(auto_now=True, verbose_name='Baja')),
                ('estatus', models.IntegerField(choices=[(0, 'Baja'), (1, 'Cancelado'), (2, 'En curso'), (3, 'En revisión'), (4, 'Suspendido'), (5, 'Terminado')], default=1, verbose_name='Estatus')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente')),
                ('empleados', models.ManyToManyField(to='rh.empleado')),
                ('vehiculos', models.ManyToManyField(to='vehiculo.vehiculo')),
            ],
            options={
                'verbose_name': 'Asignación',
                'verbose_name_plural': 'Asignaciones',
                'db_table': 'Asignacion',
                'ordering': ['-fecha_inicial'],
            },
        ),
    ]
