# Generated by Django 4.0.4 on 2024-04-11 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacion',
            name='detalle',
            field=models.TextField(blank=True, max_length=1500, null=True, verbose_name='Detalle'),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='servicio',
            field=models.IntegerField(choices=[(0, 'Sin servicio'), (1, 'Escolta mixta'), (2, 'Escolta personal'), (3, 'Escolta vehicular'), (4, 'Monitoreo'), (5, 'Seguridad en evento'), (6, 'Traslado de valores'), (7, 'Vigilancia en bienes muebles'), (99, 'Otro')], default=1, verbose_name='Servicio'),
        ),
    ]
