# Generated by Django 4.0.4 on 2024-04-12 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignacion', '0002_alter_asignacion_detalle_alter_asignacion_servicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacion',
            name='estatus',
            field=models.IntegerField(choices=[(0, 'Baja'), (1, 'Cancelado'), (2, 'En curso'), (3, 'En revisión'), (4, 'Nuevo'), (5, 'Suspendido'), (6, 'Terminado')], default=4, verbose_name='Estatus'),
        ),
    ]
