# Generated by Django 4.0.4 on 2024-04-18 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asignacion', '0004_alter_asignacion_ubicacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoAsignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(max_length=2000, verbose_name='Descripción')),
                ('seguimiento', models.JSONField(blank=True, null=True, verbose_name='Seguimiento')),
                ('fecha_alta', models.DateField(auto_now_add=True, verbose_name='Alta')),
                ('fecha_modificacion', models.DateField(auto_now=True, verbose_name='Modificación')),
                ('estatus', models.IntegerField(choices=[(0, 'Cancelado'), (1, 'En curso'), (2, 'Terminado')], default=4, verbose_name='Estatus')),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asignacion.asignacion')),
            ],
            options={
                'verbose_name': 'Evento Asignación',
                'verbose_name_plural': 'Eventos Asignación',
                'db_table': 'EventoAsignacion',
                'ordering': ['asignacion', '-fecha_alta'],
            },
        ),
    ]
