# Generated by Django 4.0.4 on 2024-04-18 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignacion', '0005_eventoasignacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoasignacion',
            name='tipo',
            field=models.IntegerField(choices=[(0, 'Suspensión'), (1, 'Incidente'), (2, 'Otro')], default=4, verbose_name='Tipo'),
        ),
    ]
