# Generated by Django 4.0.4 on 2024-04-18 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignacion', '0006_eventoasignacion_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventoasignacion',
            name='estatus',
            field=models.IntegerField(choices=[(0, 'Cancelado'), (1, 'En curso'), (2, 'Terminado')], default=1, verbose_name='Estatus'),
        ),
        migrations.AlterField(
            model_name='eventoasignacion',
            name='tipo',
            field=models.IntegerField(choices=[(0, 'Suspensión'), (1, 'Incidente'), (2, 'Otro')], default=0, verbose_name='Tipo'),
        ),
    ]
