# Generated by Django 4.0.4 on 2024-04-18 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignacion', '0007_alter_eventoasignacion_estatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventoasignacion',
            name='tipo',
            field=models.IntegerField(choices=[(0, 'Suspensión'), (1, 'Incidente'), (2, 'Comentario'), (3, 'Otro')], default=0, verbose_name='Tipo'),
        ),
    ]
