# Generated by Django 4.0.4 on 2024-03-29 18:58

import django.contrib.auth.mixins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=35, null=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=35, verbose_name='Nombre')),
                ('paterno', models.CharField(max_length=35, verbose_name='Paterno')),
                ('materno', models.CharField(max_length=35, verbose_name='Materno')),
                ('rfc', models.CharField(blank=True, max_length=18, null=True, verbose_name='R.F.C.')),
                ('curp', models.CharField(max_length=18, verbose_name='CURP')),
                ('genero', models.IntegerField(choices=[(0, 'Masculino'), (1, 'Femenino')], verbose_name='Género')),
                ('estatus', models.IntegerField(choices=[(0, 'Baja'), (1, 'Activo')], verbose_name='Estatus')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': 'Empleado',
                'ordering': ['paterno', 'materno', 'nombre'],
                'unique_together': {('curp',)},
            },
            bases=(models.Model, django.contrib.auth.mixins.PermissionRequiredMixin),
        ),
        migrations.CreateModel(
            name='Generales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domicilio', models.JSONField()),
                ('beneficiario', models.JSONField()),
                ('estudio', models.JSONField()),
                ('esperincia', models.JSONField()),
                ('familia', models.JSONField()),
                ('idioma', models.JSONField()),
                ('referencia', models.JSONField()),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rh.empleado')),
            ],
            options={
                'verbose_name': 'General',
                'verbose_name_plural': 'Generales',
                'db_table': 'Generales',
            },
            bases=(models.Model, django.contrib.auth.mixins.PermissionRequiredMixin),
        ),
    ]
