# Generated by Django 4.0.4 on 2024-03-29 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generales',
            name='beneficiario',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='generales',
            name='esperincia',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='generales',
            name='estudio',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='generales',
            name='familia',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='generales',
            name='idioma',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='generales',
            name='referencia',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
