# Generated by Django 4.0.4 on 2024-03-29 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0002_alter_generales_beneficiario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='materno',
            field=models.CharField(blank=True, max_length=35, null=True, verbose_name='Materno'),
        ),
    ]
