# Generated by Django 4.0.4 on 2024-04-12 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0002_alter_empleado_estatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='estatus',
            field=models.IntegerField(choices=[(0, 'Asignado'), (1, 'Baja'), (2, 'Sin Asignar'), (3, 'Suspendido'), (99, 'Otro')], default=2, verbose_name='Estatus'),
        ),
    ]
