# Generated by Django 4.0.4 on 2024-03-29 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0003_alter_empleado_materno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='estatus',
            field=models.IntegerField(choices=[(0, 'Baja'), (1, 'Activo')], default=1, verbose_name='Estatus'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='genero',
            field=models.IntegerField(choices=[(0, 'Masculino'), (1, 'Femenino')], default=1, verbose_name='Género'),
        ),
    ]
