# Generated by Django 4.0.4 on 2024-03-30 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0004_alter_empleado_estatus_alter_empleado_genero'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generales',
            old_name='estudio',
            new_name='escolaridad',
        ),
    ]
