# Generated by Django 4.0.4 on 2024-03-30 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0005_rename_estudio_generales_escolaridad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generales',
            old_name='esperincia',
            new_name='experiencia',
        ),
    ]
