# Generated by Django 4.0.4 on 2024-04-10 00:05

import django.contrib.auth.mixins
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fisica_moral', models.IntegerField(choices=[(0, 'Física'), (1, 'Moral')], default=0, verbose_name='Física/Moral')),
                ('razon', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre')),
                ('nombre', models.CharField(blank=True, max_length=35, null=True, verbose_name='Nombre')),
                ('paterno', models.CharField(blank=True, max_length=35, null=True, verbose_name='Paterno')),
                ('materno', models.CharField(blank=True, max_length=35, null=True, verbose_name='Materno')),
                ('rfc', models.CharField(blank=True, max_length=18, null=True, verbose_name='R.F.C.')),
                ('curp', models.CharField(blank=True, max_length=18, null=True, verbose_name='CURP')),
                ('domicilio', models.JSONField(blank=True, null=True, verbose_name='Domicilio')),
                ('fecha_alta', models.DateField(default=django.utils.timezone.now, verbose_name='Alta')),
                ('fecha_baja', models.DateField(blank=True, null=True, verbose_name='Baja')),
                ('estatus', models.IntegerField(choices=[(0, 'Baja'), (1, 'Activo')], default=1, verbose_name='Estatus')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'Cliente',
                'ordering': ['fisica_moral', 'razon', 'paterno', 'materno', 'nombre'],
            },
            bases=(models.Model, django.contrib.auth.mixins.PermissionRequiredMixin),
        ),
    ]
