# Generated by Django 4.0.4 on 2024-03-29 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['last_name', 'materno', 'first_name'], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='celular',
        ),
        migrations.AddField(
            model_name='usuario',
            name='materno',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Materno'),
        ),
    ]
