# Generated by Django 4.0.4 on 2024-04-10 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Armamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_alta', models.DateField(auto_created=True)),
                ('tipo_arma', models.IntegerField(choices=[(1, 'Ametralladora ligera'), (2, 'Ametralladora pesada'), (3, 'Escopeta'), (4, 'Fusil de asalto'), (5, 'Pistola'), (6, 'Revólver'), (99, 'Otro')], default=1)),
                ('otro_tipo_arma', models.CharField(blank=True, max_length=100, null=True)),
                ('marca', models.IntegerField(choices=[(1, 'Beretta'), (2, 'Browning'), (3, 'Colt'), (4, 'CZ (Česká zbrojovka)'), (5, 'FN Herstal'), (6, 'Glock'), (7, 'Heckler & Koch (H&K)'), (8, 'Mossberg'), (9, 'Remington'), (10, 'Ruger'), (11, 'SIG Sauer'), (12, 'Smith & Wesson'), (13, 'Springfield Armory'), (14, 'Taurus'), (15, 'Winchester'), (99, 'Otra')], default=1)),
                ('otra_marca', models.CharField(blank=True, max_length=100, null=True)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('calibre', models.IntegerField(choices=[(1, '12 Gauge (Calibre 12)'), (2, '20 Gauge (Calibre 20)'), (3, '.357 Magnum (9x33mmR)'), (4, '.38 Special (9x29mmR)'), (5, '.380 ACP (9x17mm)'), (6, '.44 Magnum (10.9x33mmR)'), (7, '.45 ACP (11.43x23mm)'), (8, '5.56x45mm NATO (.223 Remington)'), (9, '7.62x51mm NATO (.308 Winchester)'), (10, '9mm Parabellum (9x19mm)'), (99, 'Otro')], default=1)),
                ('otro_calibre', models.CharField(blank=True, max_length=100, null=True)),
                ('capacidad_cargador', models.IntegerField()),
                ('numero_serie', models.CharField(max_length=100)),
                ('fecha_baja', models.DateField(blank=True, null=True)),
                ('estatus', models.IntegerField(choices=[(0, 'Baja'), (1, 'Sin Asignar'), (2, 'Asignado'), (3, 'Taller'), (4, 'Otro')], default=1)),
            ],
            options={
                'verbose_name': 'Armamento',
                'verbose_name_plural': 'Armas',
                'db_table': 'Armamento',
                'ordering': ['numero_serie'],
                'unique_together': {('numero_serie',)},
            },
        ),
    ]
