# Generated by Django 4.0.4 on 2024-04-02 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armamento', '0002_alter_armamento_calibre_alter_armamento_marca_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='armamento',
            name='fecha_baja',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='armamento',
            name='fecha_registro',
            field=models.DateField(auto_created=True),
        ),
    ]
