# Generated by Django 4.0.4 on 2024-04-02 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('armamento', '0003_armamento_fecha_baja_alter_armamento_fecha_registro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='armamento',
            old_name='otro_tipo',
            new_name='otro_tipo_arma',
        ),
        migrations.RenameField(
            model_name='armamento',
            old_name='tipo',
            new_name='tipo_arma',
        ),
    ]
