# Generated by Django 4.0.4 on 2024-04-02 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armamento', '0005_rename_fecha_registro_armamento_fecha_alta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armamento',
            name='estatus',
            field=models.CharField(choices=[(0, 'Baja'), (1, 'Sin Asignar'), (2, 'Asignado'), (3, 'Taller'), (4, 'Otro')], default=1, max_length=100),
        ),
    ]
