# Generated by Django 4.0.4 on 2024-04-02 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armamento', '0006_alter_armamento_estatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armamento',
            name='numero_serie',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='armamento',
            unique_together={('numero_serie',)},
        ),
    ]
