# Generated by Django 4.0.4 on 2024-04-02 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armamento', '0008_alter_armamento_calibre_alter_armamento_estatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armamento',
            name='calibre',
            field=models.IntegerField(choices=[(1, '12 Gauge (Calibre 12)'), (2, '20 Gauge (Calibre 20)'), (3, '.357 Magnum (9x33mmR)'), (4, '.38 Special (9x29mmR)'), (5, '.380 ACP (9x17mm)'), (6, '.44 Magnum (10.9x33mmR)'), (7, '.45 ACP (11.43x23mm)'), (8, '5.56x45mm NATO (.223 Remington)'), (9, '7.62x51mm NATO (.308 Winchester)'), (10, '9mm Parabellum (9x19mm)'), (99, 'Otro')], default=1),
        ),
        migrations.AlterField(
            model_name='armamento',
            name='marca',
            field=models.IntegerField(choices=[(1, 'Beretta'), (2, 'Browning'), (3, 'Colt'), (4, 'CZ (Česká zbrojovka)'), (5, 'FN Herstal'), (6, 'Glock'), (7, 'Heckler & Koch (H&K)'), (8, 'Mossberg'), (9, 'Remington'), (10, 'Ruger'), (11, 'SIG Sauer'), (12, 'Smith & Wesson'), (13, 'Springfield Armory'), (14, 'Taurus'), (15, 'Winchester'), (99, 'Otro')], default=1),
        ),
        migrations.AlterField(
            model_name='armamento',
            name='tipo_arma',
            field=models.IntegerField(choices=[(1, 'Ametralladora ligera'), (2, 'Ametralladora pesada'), (3, 'Escopeta'), (4, 'Fusil de asalto'), (5, 'Pistola'), (6, 'Revólver'), (99, 'Otro')], default=1),
        ),
    ]
