# Generated by Django 4.0.4 on 2024-04-02 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armamento', '0009_alter_armamento_calibre_alter_armamento_marca_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armamento',
            name='estatus',
            field=models.IntegerField(choices=[(0, 'Baja'), (1, 'Sin Asignar'), (2, 'Asignado'), (3, 'Taller'), (4, 'Otro')], default=1),
        ),
    ]
