# Generated by Django 4.0.4 on 2024-04-03 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armamento', '0010_alter_armamento_estatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armamento',
            name='marca',
            field=models.IntegerField(choices=[(1, 'Beretta'), (2, 'Browning'), (3, 'Colt'), (4, 'CZ (Česká zbrojovka)'), (5, 'FN Herstal'), (6, 'Glock'), (7, 'Heckler & Koch (H&K)'), (8, 'Mossberg'), (9, 'Remington'), (10, 'Ruger'), (11, 'SIG Sauer'), (12, 'Smith & Wesson'), (13, 'Springfield Armory'), (14, 'Taurus'), (15, 'Winchester'), (99, 'Otra')], default=1),
        ),
    ]
