# Generated by Django 4.0.4 on 2024-05-06 23:45

import django.contrib.auth.mixins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rh', '0003_alter_empleado_estatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro', models.DateTimeField(blank=True, null=True, verbose_name='Registro')),
                ('longitud', models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True, verbose_name='Longitud')),
                ('latitud', models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True, verbose_name='Latitud')),
                ('fecha_alta', models.DateField(auto_now_add=True, verbose_name='Alta')),
                ('fecha_modificacion', models.DateField(auto_now=True, verbose_name='Modificación')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rh.empleado')),
            ],
            options={
                'verbose_name': 'Ubicación',
                'verbose_name_plural': 'Ubicaciones',
                'db_table': 'Seguimiento',
                'ordering': ['empleado', '-registro'],
            },
            bases=(models.Model, django.contrib.auth.mixins.PermissionRequiredMixin),
        ),
    ]
