# Generated by Django 4.0.4 on 2024-05-07 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguimiento',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Latitud'),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Longitud'),
        ),
    ]
