# Generated by Django 4.0.4 on 2024-04-01 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(choices=[(0, 'Toyota'), (2, 'Ford'), (3, 'Chevrolet'), (4, 'Honda'), (5, 'Volkswagen'), (6, 'Nissan'), (7, 'BMW'), (8, 'Mercedes-Benz'), (9, 'Audi'), (10, 'Hyundai'), (11, 'Kia'), (12, 'Subaru'), (13, 'Mazda'), (14, 'Tesla'), (15, 'Lexus'), (16, 'Otro')], default=1, max_length=100)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('año', models.IntegerField()),
                ('placa', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('color', models.CharField(max_length=50)),
                ('tipo_combustible', models.CharField(choices=[(0, 'Gasolina Magna (Regular)'), (1, 'Gasolina Premium'), (2, 'Diésel'), (3, 'Gas LP'), (4, 'Otro')], default=1, max_length=50)),
                ('otro_tipo_combustible', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_vehiculo', models.CharField(choices=[(0, 'Automóvil'), (1, 'Camioneta'), (2, 'Camión'), (3, 'Motocicleta'), (4, 'Autobús'), (5, 'Furgoneta'), (6, 'SUV (Vehículo utilitario deportivo)'), (7, 'RV (Vehículo recreativo)'), (8, 'Bicicleta'), (9, 'Otro')], default=1, max_length=50)),
                ('numero_serie', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_alta', models.DateField(auto_now_add=True)),
                ('fecha_baja', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Vehiculo',
                'verbose_name_plural': 'Vehiculos',
                'db_table': 'Vehiculo',
                'ordering': ['placa'],
            },
        ),
    ]
