# Generated by Django 4.0.4 on 2024-04-10 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.IntegerField(choices=[(1, 'Audi'), (2, 'BMW'), (3, 'Chevrolet'), (4, 'Ford'), (5, 'Honda'), (6, 'Hyundai'), (7, 'Kia'), (8, 'Lexus'), (9, 'Mazda'), (10, 'Mercedes-Benz'), (11, 'Nissan'), (12, 'Subaru'), (13, 'Tesla'), (14, 'Toyota'), (15, 'Volkswagen'), (99, 'Otra')], default=1, verbose_name='Marca')),
                ('otra_marca', models.CharField(blank=True, max_length=100, null=True, verbose_name='Otra marca')),
                ('modelo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Modelo')),
                ('anio', models.IntegerField(verbose_name='Año')),
                ('placa', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Placa')),
                ('color', models.CharField(max_length=50, verbose_name='Color')),
                ('tipo_combustible', models.IntegerField(choices=[(1, 'Diésel'), (2, 'Gas LP'), (3, 'Gasolina Magna (Regular)'), (4, 'Gasolina Premium'), (5, 'Eléctrico'), (99, 'Otro')], default=1, verbose_name='Combustible')),
                ('otro_tipo_combustible', models.CharField(blank=True, max_length=50, null=True, verbose_name='Otro combustible')),
                ('tipo_vehiculo', models.IntegerField(choices=[(1, 'Autobús'), (2, 'Automóvil'), (3, 'Bicicleta'), (4, 'Camión'), (5, 'Camioneta'), (6, 'Furgoneta'), (7, 'Motocicleta'), (8, 'RV (Vehículo recreativo)'), (9, 'SUV (Vehículo utilitario deportivo)'), (99, 'Otro')], default=1, verbose_name='Tipo vehículo')),
                ('otro_tipo_vehiculo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Otro tipo de Vehículo')),
                ('numero_serie', models.CharField(max_length=50, verbose_name='Número serie')),
                ('fecha_alta', models.DateField(verbose_name='Alta')),
                ('fecha_baja', models.DateField(blank=True, null=True, verbose_name='Baja')),
                ('estatus', models.IntegerField(choices=[(0, 'Baja'), (1, 'Sin Asignar'), (2, 'Asignado'), (3, 'Taller'), (4, 'Otro')], default=1, verbose_name='Estatus')),
            ],
            options={
                'verbose_name': 'Vehiculo',
                'verbose_name_plural': 'Vehiculos',
                'db_table': 'Vehiculo',
                'ordering': ['placa'],
            },
        ),
    ]
