# Generated by Django 4.0.4 on 2024-04-17 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0002_alter_vehiculo_estatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='estatus',
            field=models.IntegerField(choices=[(0, 'Asignado'), (1, 'Baja'), (2, 'Sin Asignar'), (3, 'Taller'), (99, 'Otro')], default=2, verbose_name='Estatus'),
        ),
    ]
