# Generated by Django 4.0.4 on 2024-04-01 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0002_rename_año_vehiculo_anio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='anio',
            field=models.IntegerField(verbose_name='Año'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='color',
            field=models.CharField(max_length=50, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='fecha_alta',
            field=models.DateField(auto_now_add=True, verbose_name='Alta'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='fecha_baja',
            field=models.DateField(blank=True, null=True, verbose_name='Baja'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='marca',
            field=models.CharField(choices=[(0, 'Toyota'), (2, 'Ford'), (3, 'Chevrolet'), (4, 'Honda'), (5, 'Volkswagen'), (6, 'Nissan'), (7, 'BMW'), (8, 'Mercedes-Benz'), (9, 'Audi'), (10, 'Hyundai'), (11, 'Kia'), (12, 'Subaru'), (13, 'Mazda'), (14, 'Tesla'), (15, 'Lexus'), (16, 'Otro')], default=1, max_length=100, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='modelo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='numero_serie',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número serie'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='otro_tipo_combustible',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Otro combustible'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='placa',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Placa'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='tipo_combustible',
            field=models.CharField(choices=[(0, 'Gasolina Magna (Regular)'), (1, 'Gasolina Premium'), (2, 'Diésel'), (3, 'Gas LP'), (4, 'Otro')], default=1, max_length=50, verbose_name='Combustible'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='tipo_vehiculo',
            field=models.CharField(choices=[(0, 'Automóvil'), (1, 'Camioneta'), (2, 'Camión'), (3, 'Motocicleta'), (4, 'Autobús'), (5, 'Furgoneta'), (6, 'SUV (Vehículo utilitario deportivo)'), (7, 'RV (Vehículo recreativo)'), (8, 'Bicicleta'), (9, 'Otro')], default=1, max_length=50, verbose_name='Tipo vehículo'),
        ),
    ]
