# Generated by Django 4.0.4 on 2024-04-01 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0003_alter_vehiculo_anio_alter_vehiculo_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='fecha_alta',
            field=models.DateField(verbose_name='Alta'),
        ),
    ]
