# Generated by Django 4.0.4 on 2024-04-01 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0004_alter_vehiculo_fecha_alta'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='estatus',
            field=models.CharField(choices=[(0, 'Baja'), (1, 'Sin Asignar'), (2, 'Asignado'), (3, 'Taller'), (4, 'Otro')], default='', max_length=2, verbose_name='Estatus'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='marca',
            field=models.CharField(choices=[(0, 'Toyota'), (2, 'Ford'), (3, 'Chevrolet'), (4, 'Honda'), (5, 'Volkswagen'), (6, 'Nissan'), (7, 'BMW'), (8, 'Mercedes-Benz'), (9, 'Audi'), (10, 'Hyundai'), (11, 'Kia'), (12, 'Subaru'), (13, 'Mazda'), (14, 'Tesla'), (15, 'Lexus'), (16, 'Otro')], default=1, max_length=2, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='tipo_combustible',
            field=models.CharField(choices=[(0, 'Gasolina Magna (Regular)'), (1, 'Gasolina Premium'), (2, 'Diésel'), (3, 'Gas LP'), (4, 'Otro')], default=1, max_length=2, verbose_name='Combustible'),
        ),
    ]
