# Generated by Django 4.0.4 on 2024-04-01 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0005_vehiculo_estatus_alter_vehiculo_marca_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='tipo_vehiculo',
            field=models.CharField(choices=[(0, 'Automóvil'), (1, 'Camioneta'), (2, 'Camión'), (3, 'Motocicleta'), (4, 'Autobús'), (5, 'Furgoneta'), (6, 'SUV (Vehículo utilitario deportivo)'), (7, 'RV (Vehículo recreativo)'), (8, 'Bicicleta'), (9, 'Otro')], default=1, max_length=2, verbose_name='Tipo vehículo'),
        ),
    ]
