# Generated by Django 4.0.4 on 2024-04-01 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0008_alter_vehiculo_estatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='estatus',
            field=models.CharField(default=0, max_length=2, verbose_name='Estatus'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='marca',
            field=models.CharField(choices=[(0, 'Toyota'), (2, 'Ford'), (3, 'Chevrolet'), (4, 'Honda'), (5, 'Volkswagen'), (6, 'Nissan'), (7, 'BMW'), (8, 'Mercedes-Benz'), (9, 'Audi'), (10, 'Hyundai'), (11, 'Kia'), (12, 'Subaru'), (13, 'Mazda'), (14, 'Tesla'), (15, 'Lexus'), (16, 'Otro')], default=0, max_length=2, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='tipo_combustible',
            field=models.CharField(choices=[(0, 'Gasolina Magna (Regular)'), (1, 'Gasolina Premium'), (2, 'Diésel'), (3, 'Gas LP'), (4, 'Otro')], default=0, max_length=2, verbose_name='Combustible'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='tipo_vehiculo',
            field=models.CharField(choices=[(0, 'Automóvil'), (1, 'Camioneta'), (2, 'Camión'), (3, 'Motocicleta'), (4, 'Autobús'), (5, 'Furgoneta'), (6, 'SUV (Vehículo utilitario deportivo)'), (7, 'RV (Vehículo recreativo)'), (8, 'Bicicleta'), (9, 'Otro')], default=0, max_length=2, verbose_name='Tipo vehículo'),
        ),
    ]
