# Generated by Django 4.0.4 on 2024-04-01 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0009_alter_vehiculo_estatus_alter_vehiculo_marca_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='estatus',
            field=models.CharField(choices=[(0, 'Baja'), (1, 'Sin Asignar'), (2, 'Asignado'), (3, 'Taller'), (4, 'Otro')], default=1, max_length=2, verbose_name='Estatus'),
        ),
    ]
