# Generated by Django 4.0.4 on 2024-04-01 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0010_alter_vehiculo_estatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='estatus',
            field=models.IntegerField(choices=[(0, 'Baja'), (1, 'Sin Asignar'), (2, 'Asignado'), (3, 'Taller'), (4, 'Otro')], default=1, verbose_name='Estatus'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='marca',
            field=models.IntegerField(choices=[(1, 'Audi'), (2, 'BMW'), (3, 'Chevrolet'), (4, 'Ford'), (5, 'Honda'), (6, 'Hyundai'), (7, 'Kia'), (8, 'Lexus'), (9, 'Mazda'), (10, 'Mercedes-Benz'), (11, 'Nissan'), (12, 'Subaru'), (13, 'Tesla'), (14, 'Toyota'), (15, 'Volkswagen'), (99, 'Otro')], default=1, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='tipo_combustible',
            field=models.IntegerField(choices=[(1, 'Diésel'), (2, 'Gas LP'), (3, 'Gasolina Magna (Regular)'), (4, 'Gasolina Premium'), (99, 'Otro')], default=1, verbose_name='Combustible'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='tipo_vehiculo',
            field=models.IntegerField(choices=[(1, 'Autobús'), (2, 'Automóvil'), (3, 'Bicicleta'), (4, 'Camión'), (5, 'Camioneta'), (6, 'Furgoneta'), (7, 'Motocicleta'), (8, 'RV (Vehículo recreativo)'), (9, 'SUV (Vehículo utilitario deportivo)'), (99, 'Otro')], default=1, verbose_name='Tipo vehículo'),
        ),
    ]
