# Generated by Django 4.0.4 on 2024-04-02 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0011_alter_vehiculo_estatus_alter_vehiculo_marca_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='otra_marca',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Otra marca'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='otro_tipo_vehiculo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Otro tipo de Vehículo'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='tipo_combustible',
            field=models.IntegerField(choices=[(1, 'Diésel'), (2, 'Gas LP'), (3, 'Gasolina Magna (Regular)'), (4, 'Gasolina Premium'), (5, 'Eléctrico'), (99, 'Otro')], default=1, verbose_name='Combustible'),
        ),
    ]
