# Generated by Django 4.0.4 on 2024-04-02 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0012_vehiculo_otra_marca_vehiculo_otro_tipo_vehiculo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='numero_serie',
            field=models.CharField(max_length=50, verbose_name='Número serie'),
        ),
    ]
